# Generated by Django 3.2.5 on 2021-07-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_modidied',
            new_name='date_modified',
        ),
    ]
